#!/bin/sh
set -eu
case "$1" in
    remove|upgrade|deconfigure)
        if [ -d /run/systemd/system ]; then
            deb-systemd-invoke stop clash-manager.service clash-manager-helper.service || true
        fi
        ;;
esac
